trigger:
  - develop

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.12'
    displayName: 'Install Node.js'

  - script: |
      echo "VITE_CLIENT_ID=$(CLIENT_ID)" >> .env
      echo "VITE_AUTHORITY=$(AUTHORITY)" >> .env
      echo "VITE_API_SCOPES=$(API_SCOPES)" >> .env
      echo "VITE_REDIRECT_URI=$(URI_DEV_URL)" >> .env
      echo "VITE_API_PES_URL=$(API_PES_URL)" >> .env

      npm install
      npm run build
    displayName: 'npm install and build'

  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/dist'
      output_location: ''
      azure_static_web_apps_api_token: $(app_token)